name: Build Android APK

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v5
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.4'
        cache-disabled: 'true'

    - name: Run Build
      run: gradle assembleDebug

    - name: Upload APK to Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/heads/')
      with:
        files: app/build/outputs/apk/debug/*.apk
        tag_name: v1.0.0
        overwrite: true
        body: "نسخة أداة Hema Repost Cleaner التلقائية لجهازك."
